# Generated by Django 3.1.7 on 2021-02-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrcode', models.ImageField(blank=True, upload_to='qr_codes')),
                ('nquadro', models.CharField(max_length=50)),
                ('ordem', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('ndisplay', models.CharField(max_length=50)),
                ('nmotor', models.CharField(max_length=50)),
                ('linha', models.CharField(choices=[('1', 'Linha 1'), ('2', 'Linha 2')], default='', max_length=1)),
            ],
        ),
    ]
