# Generated by Django 3.1.7 on 2021-02-25 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premontagem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='linha',
            field=models.CharField(choices=[('1', 'Linha 1'), ('2', 'Linha 2')], default='', max_length=1, verbose_name='Linha de Montagem'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='marca',
            field=models.CharField(max_length=50, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='modelo',
            field=models.CharField(max_length=50, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='ndisplay',
            field=models.CharField(max_length=50, verbose_name='Número Display'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='nmotor',
            field=models.CharField(max_length=50, verbose_name='Número do Motor'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='nquadro',
            field=models.CharField(max_length=50, verbose_name='Número do Quadro'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='ordem',
            field=models.CharField(max_length=50, verbose_name='Número da Ordem'),
        ),
    ]
