# Generated by Django 3.1.7 on 2021-02-28 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premontagem', '0003_auto_20210226_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='barcode',
        ),
    ]
