# Generated by Django 3.1.7 on 2021-02-28 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premontagem', '0004_remove_bike_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='id',
        ),
        migrations.AlterField(
            model_name='bike',
            name='nquadro',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Número do Quadro'),
        ),
    ]
