# Generated by Django 3.1.7 on 2021-03-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premontagem', '0005_auto_20210228_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='genero',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], default='M', max_length=2, verbose_name='Gênero'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bike',
            name='mudanca',
            field=models.CharField(choices=[('1', 'OK'), ('2', 'Desafinado'), ('3', 'Não Feito')], default='3', max_length=2, verbose_name='Mudança: '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bike',
            name='nbateria',
            field=models.CharField(default=0, max_length=50, verbose_name='Número da Bateria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bike',
            name='ncontrolador',
            field=models.CharField(default=0, max_length=50, verbose_name='Número do Controlador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bike',
            name='tamanho',
            field=models.CharField(choices=[('44', '44'), ('46', '46'), ('49', '49'), ('53', '53'), ('54', '54'), ('58', '58')], default='44', max_length=2, verbose_name='Tamanho'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bike',
            name='travaofrente',
            field=models.CharField(choices=[('1', 'OK'), ('2', 'Desafinado'), ('3', 'Não Feito')], default=3, max_length=2, verbose_name='Travão Frente: '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bike',
            name='travaotras',
            field=models.CharField(choices=[('1', 'OK'), ('2', 'Desafinado'), ('3', 'Não Feito')], default=3, max_length=2, verbose_name='Travão Tras: '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bike',
            name='linha',
            field=models.CharField(choices=[('L1', 'Linha 1'), ('L2', 'Linha 2')], max_length=2, verbose_name='Linha de Montagem'),
        ),
    ]
