# Generated by Django 3.1.7 on 2021-03-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premontagem', '0006_auto_20210303_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='marca',
            field=models.CharField(blank=True, max_length=50, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='modelo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='nbateria',
            field=models.CharField(blank=True, max_length=50, verbose_name='Número da Bateria'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='ncontrolador',
            field=models.CharField(blank=True, max_length=50, verbose_name='Número do Controlador'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='ndisplay',
            field=models.CharField(blank=True, max_length=50, verbose_name='Número Display'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='nmotor',
            field=models.CharField(blank=True, max_length=50, verbose_name='Número do Motor'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='nquadro',
            field=models.CharField(blank=True, max_length=50, primary_key=True, serialize=False, verbose_name='Número do Quadro'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='ordem',
            field=models.CharField(blank=True, max_length=50, verbose_name='Número da Ordem'),
        ),
    ]
