# Generated by Django 3.1.7 on 2021-03-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premontagem', '0007_auto_20210303_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição do defeito'),
        ),
        migrations.AddField(
            model_name='bike',
            name='imagem',
            field=models.ImageField(null=True, upload_to='', verbose_name='Imagem do defeito'),
        ),
    ]
